os: linux
dist: bionic

language: ruby
rvm: 2.6.5

before_install:
  - bundle config path 'vendor/bundle'

install:
  - bundle install --quiet

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

script:
  - >-
    git clone https://${GH_PAT}@github.com/${GH_USER}/${BUILDER_REPO}.git
    ${HOME}/${BUILDER_REPO} --depth=1 -q
  - cp -r ${HOME}/${BUILDER_REPO}/framework/* .
  - bash _cibuild.sh

branches:
  only: master

git:
  depth: false # for posts lastmod

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor/bundle

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer